services:
  cache-service:
    image: redis:7.4.2-alpine
    hostname: cache-service
    container_name: url-shortener-cache-service
    ports:
      - "${CACHE_SERVICE_PORT}:6379"
    networks:
      - application-network
    environment:
      REDIS_USER: ${CACHE_SERVICE_HOST}
      REDIS_PASSWORD: ${CACHE_SERVICE_PASSWORD}

  database:
    image: mongo
    restart: always
    hostname: database
    container_name: url-shortener-database
    ports:
      - "${DATABASE_PORT}:27017"
    networks:
      - application-network
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  server:
    container_name: url-shortener-server
    depends_on:
      - cache-service
      - database
    ports:
      - '3000:${SERVER_PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 45s
      timeout: 5s
      retries: 5
      start_period: 5s
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    networks:
      - application-network
    environment:
      - PORT=${SERVER_PORT}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  stress-test-application:
    container_name: url-shortener-stress-test-application
    profiles:
      - stress-test
    depends_on:
      server:
        condition: service_healthy
    ports:
      - '5665:${STRESS_TEST_DASHBOARD_PORT}'
    build:
      context: .
      dockerfile: apps/backend-e2e/Dockerfile
    networks:
      - application-network
    environment:
      - API_URL=${API_URL}
      - K6_WEB_DASHBOARD=${STRESS_TEST_DASHBOARD}
      - K6_WEB_DASHBOARD_HOST=${STRESS_TEST_DASHBOARD_HOST}
      - K6_WEB_DASHBOARD_PORT=${STRESS_TEST_DASHBOARD_PORT}
      - K6_WEB_DASHBOARD_OPEN=${STRESS_TEST_DASHBOARD_OPEN}
      - K6_WEB_DASHBOARD_PERIOD=${STRESS_TEST_DASHBOARD_PERIOD}
      - K6_WEB_DASHBOARD_EXPORT=${STRESS_TEST_DASHBOARD_EXPORT}

networks:
  application-network:
    driver: bridge
