### Variables
@apiUrl = http://localhost:3000

### Urls ###

### POST Url
POST {{apiUrl}}/api/url HTTP/1.1
content-type: application/json

{
    "uri": "https://www.youtube.com/"
}

### GET All Urls
GET {{apiUrl}}/api/url HTTP/1.1

### GET Url by ID
GET {{apiUrl}}/api/url/1 HTTP/1.1

### REDIRECT Url by Encoded URI
GET {{apiUrl}}/url/1 HTTP/1.1
