services:
  cache-service:
    image: redis:7.4.2-alpine
    hostname: cache-service
    container_name: url-shortener-cache-service
    ports:
      - "${CACHE_SERVICE_PORT}:6379"
    environment:
      REDIS_USER: ${CACHE_SERVICE_HOST}
      REDIS_PASSWORD: ${CACHE_SERVICE_PASSWORD}

  database:
    image: mongo
    restart: always
    hostname: database
    container_name: url-shortener-database
    ports:
      - "${DATABASE_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
